# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.83895806 0.3478071  0.89371101]
  [0.58719633 0.82014555 0.67062665]
  [0.36130771 0.44915712 0.89078728]]

 [[0.31182812 0.17806278 0.72738874]
  [0.53628053 0.15951141 0.78599884]
  [0.33410221 0.14789261 0.97169191]]

 [[0.63650629 0.93145093 0.7290588 ]
  [0.44028543 0.63763608 0.20635371]
  [0.43160881 0.32739589 0.167235  ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
y=np.array([(1,2,3,4,5),(1,2,3,4,5),(1,2,3,4,5),(1,2,3,4,5),(1,2,3,4,5)])
x = np.diag([1, 2, 3, 4, 5])
print(x)   
print(y)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [10]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.71202574 0.20302865 0.28317235 0.12269414 0.99857456]
 [0.79612051 0.87816841 0.59662013 0.84428193 0.27019155]
 [0.37887567 0.83034201 0.85270646 0.31873128 0.6364449 ]
 [0.06449969 0.38447455 0.25156976 0.9041429  0.39118618]
 [0.49291931 0.03911444 0.11490352 0.5326308  0.99872366]]
After normalization:
[[0.70123471 0.1708135  0.25433051 0.08709764 0.99984462]
 [0.78886911 0.87437047 0.58097158 0.83905768 0.24080334]
 [0.35406208 0.82453102 0.84783681 0.29138615 0.62247262]
 [0.02645373 0.35989662 0.22139775 0.90143825 0.36689074]
 [0.4729059  0.         0.0789791  0.51428889 1.        ]]


# 5.  How to find common values between two arrays?

In [11]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [12]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [13]:
A = np.random.randint(0,2,6)
print("First array:")
print(A)
B = np.random.randint(0,2,6)
print("Second array:")
print(B)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(A, B)
print(array_equal)

First array:
[0 0 0 0 0 0]
Second array:
[1 1 1 0 0 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.68432461 0.09590467 0.56752068 0.65274911 0.97513469 0.7749266
 0.49737258 0.13873533 0.42223994 0.76596278]
Maximum value replaced by 0:
[0.68432461 0.09590467 0.56752068 0.65274911 0.         0.7749266
 0.49737258 0.13873533 0.42223994 0.76596278]


# 9. How to print all the values of an array?

In [18]:
import sys
np.set_printoptions(threshold=sys.maxsize)

x = np.zeros((15, 15))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [20]:
print("Original matrix:\n")
X = np.random.rand(2, 2)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.84603864 0.9365835 ]
 [0.97526953 0.7909044 ]]

Subtract the mean of each row of the said matrix:

[[-0.04527243  0.04527243]
 [ 0.09218257 -0.09218257]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [21]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 2. 1. 4. 2. 2. 6. 4. 2. 3.]


# 12.How to get the diagonal of a dot product?

In [27]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", A, B)

array([58, 70, 90])

# 13.How to find the most frequent value in an array?

In [29]:
M = np.random.randint(0,10,50)
print (M)
print('Most frequent value:', np.bincount(M).argmax())

[5 2 3 0 9 1 2 8 5 3 1 8 5 2 2 8 3 7 6 1 4 9 0 7 4 2 5 5 8 7 8 2 8 7 7 4 8
 3 4 1 9 2 8 2 3 5 4 3 2 0]
Most frequent value: 2


# 14.How to get the n largest values of an array

In [30]:
X = np.arange(10000)
np.random.shuffle(X)
n = 5


print (X[np.argpartition(-X,n)[:n]])

[9999 9998 9997 9995 9996]


# 15.How to create a record array from a regular array?

In [36]:
S = np.array([("SWAPNIL", 2.5, 3),
              ("ENGG", 3.6, 2)])
R = np.core.records.fromarrays(S.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')


In [37]:
print (R)

[(b'SWAPNIL', 2.5, 3) (b'ENGG', 3.6, 2)]
